blank_issues_enabled: false
contact_links:
  - name: 💬 GitHub Discussions
    url: https://github.com/kcaldas/genie/discussions
    about: Ask questions and discuss ideas with the community
  - name: 📚 Documentation
    url: https://github.com/kcaldas/genie/tree/main/docs
    about: Check our comprehensive documentation
  - name: 🔒 Security Issues
    url: https://github.com/kcaldas/genie/security/advisories/new
    about: Report security vulnerabilities privately