// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package tui

import (
	"github.com/awesome-gocui/gocui"
	"github.com/google/wire"
	"github.com/kcaldas/genie/cmd/events"
	"github.com/kcaldas/genie/cmd/tui/helpers"
	"github.com/kcaldas/genie/cmd/tui/layout"
	"github.com/kcaldas/genie/cmd/tui/state"
	"github.com/kcaldas/genie/internal/di"
	"github.com/kcaldas/genie/pkg/genie"
	"path/filepath"
)

// Injectors from wire.go:

func ProvideConfigManager() (*helpers.ConfigManager, error) {
	configManager, err := helpers.NewConfigManager()
	if err != nil {
		return nil, err
	}
	return configManager, nil
}

func ProvideLayoutManager(gui *gocui.Gui) (*layout.LayoutManager, error) {
	configManager, err := ProvideConfigManager()
	if err != nil {
		return nil, err
	}
	layoutConfig := ProvideLayoutConfig(configManager)
	layoutManager := layout.NewLayoutManager(gui, layoutConfig)
	return layoutManager, nil
}

// InjectTUI - Production TUI injector (default output mode from config)
func InjectTUI(session *genie.Session) (*TUI, error) {
	configManager, err := ProvideConfigManager()
	if err != nil {
		return nil, err
	}
	gui, err := NewGocuiGui(configManager)
	if err != nil {
		return nil, err
	}
	genieGenie, err := ProvideGenie()
	if err != nil {
		return nil, err
	}
	eventsCommandEventBus := ProvideCommandEventBus()
	app, err := NewApp(gui, genieGenie, session, eventsCommandEventBus, configManager)
	if err != nil {
		return nil, err
	}
	tui := New(app)
	return tui, nil
}

// InjectTestApp - Test App injector (custom output mode)
func InjectTestApp(genieService genie.Genie, session *genie.Session, outputMode gocui.OutputMode) (*App, error) {
	gui, err := NewGocuiGuiWithOutputMode(outputMode)
	if err != nil {
		return nil, err
	}
	eventsCommandEventBus := ProvideCommandEventBus()
	configManager, err := ProvideConfigManager()
	if err != nil {
		return nil, err
	}
	app, err := NewApp(gui, genieService, session, eventsCommandEventBus, configManager)
	if err != nil {
		return nil, err
	}
	return app, nil
}

// wire.go:

// HistoryPath represents the path to the chat history file
type HistoryPath string

// Shared command event bus instance
var commandEventBus = events.NewCommandEventBus()

// Shared genie instance (singleton)
var (
	genieInstance    genie.Genie
	genieError       error
	genieInitialized bool
)

// Shared GUI instance (singleton)
var (
	guiInstance    *gocui.Gui
	guiError       error
	guiInitialized bool
)

// ProvideCommandEventBus provides a shared command event bus instance
func ProvideCommandEventBus() *events.CommandEventBus {
	return commandEventBus
}

// ProvideGenie provides a shared Genie singleton instance
func ProvideGenie() (genie.Genie, error) {
	if !genieInitialized {
		genieInstance, genieError = di.ProvideGenie()
		genieInitialized = true
	}
	return genieInstance, genieError
}

// NewGocuiGui - Production GUI provider (uses config-based output mode)
func NewGocuiGui(configManager *helpers.ConfigManager) (*gocui.Gui, error) {
	config := configManager.GetConfig()
	guiOutputMode := configManager.GetGocuiOutputMode(config.OutputMode)

	g, err := gocui.NewGui(guiOutputMode, true)
	if err != nil {
		return nil, err
	}
	return g, nil
}

// NewGocuiGuiWithOutputMode - Test/Custom GUI provider (accepts custom output mode)
func NewGocuiGuiWithOutputMode(outputMode gocui.OutputMode) (*gocui.Gui, error) {
	g, err := gocui.NewGui(outputMode, true)
	if err != nil {
		return nil, err
	}
	return g, nil
}

// ProvideHistoryPath provides the chat history file path based on session working directory
func ProvideHistoryPath(session *genie.Session) HistoryPath {
	return HistoryPath(filepath.Join(session.WorkingDirectory, ".genie", "history"))
}

func ProvideLayoutConfig(configManager *helpers.ConfigManager) *layout.LayoutConfig {
	config := configManager.GetConfig()
	return &layout.LayoutConfig{
		MessagesWeight: 3,
		InputHeight:    4,
		DebugWeight:    1,
		StatusHeight:   2,
		ShowSidebar:    config.Layout.ShowSidebar,
		CompactMode:    config.Layout.CompactMode,
		MinPanelWidth:  config.Layout.MinPanelWidth,
		MinPanelHeight: config.Layout.MinPanelHeight,
	}
}

func ProvideChatState(configManager *helpers.ConfigManager) *state.ChatState {
	config := configManager.GetConfig()
	return state.NewChatState(config.MaxChatMessages)
}

func ProvideUIState() *state.UIState {
	return state.NewUIState()
}

func ProvideDebugState() *state.DebugState {
	return state.NewDebugState()
}

func ProvideStateAccessor(chatState *state.ChatState, uiState *state.UIState) *state.StateAccessor {
	return state.NewStateAccessor(chatState, uiState)
}

// CoreDepsSet - Core dependencies (shared between production and test)
var CoreDepsSet = wire.NewSet(
	ProvideCommandEventBus,
)

// ProdAppDepsSet - Production app dependencies (includes config-based GUI)
var ProdAppDepsSet = wire.NewSet(
	CoreDepsSet,
	ProvideGenie,
	ProvideConfigManager,
	NewGocuiGui,
	NewApp,
)

// TestAppDepsSet - Test app dependencies (uses custom output mode GUI)
var TestAppDepsSet = wire.NewSet(
	CoreDepsSet,
	ProvideConfigManager,
	NewGocuiGuiWithOutputMode,
)
