// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package tui

import (
	"github.com/awesome-gocui/gocui"
	"github.com/google/wire"
	"github.com/kcaldas/genie/cmd/events"
	"github.com/kcaldas/genie/cmd/tui/component"
	"github.com/kcaldas/genie/cmd/tui/controllers"
	"github.com/kcaldas/genie/cmd/tui/helpers"
	"github.com/kcaldas/genie/cmd/tui/layout"
	"github.com/kcaldas/genie/cmd/tui/state"
	"github.com/kcaldas/genie/cmd/tui/types"
	"github.com/kcaldas/genie/internal/di"
	events2 "github.com/kcaldas/genie/pkg/events"
	"github.com/kcaldas/genie/pkg/genie"
	"path/filepath"
)

// Injectors from wire.go:

func ProvideConfigManager() (*helpers.ConfigManager, error) {
	configManager, err := helpers.NewConfigManager()
	if err != nil {
		return nil, err
	}
	return configManager, nil
}

func ProvideClipboard() *helpers.Clipboard {
	clipboard := helpers.NewClipboard()
	return clipboard
}

func ProvideMessagesComponent(gui types.Gui, chatState *state.ChatState, configManager *helpers.ConfigManager, commandEventBus2 *events.CommandEventBus, tabHandler types.TabHandler) (*component.MessagesComponent, error) {
	messagesComponent := component.NewMessagesComponent(gui, chatState, configManager, commandEventBus2, tabHandler)
	return messagesComponent, nil
}

func ProvideInputComponent(gui types.Gui, configManager *helpers.ConfigManager, commandEventBus2 *events.CommandEventBus, historyPath HistoryPath, tabHandler types.TabHandler) (*component.InputComponent, error) {
	string2 := ProvideHistoryPathString(historyPath)
	inputComponent := component.NewInputComponent(gui, configManager, commandEventBus2, string2, tabHandler)
	return inputComponent, nil
}

func ProvideStatusComponent(gui types.Gui, stateAccessor *state.StateAccessor, configManager *helpers.ConfigManager, commandEventBus2 *events.CommandEventBus) (*component.StatusComponent, error) {
	statusComponent := component.NewStatusComponent(gui, stateAccessor, configManager, commandEventBus2)
	return statusComponent, nil
}

func ProvideTextViewerComponent(gui types.Gui, configManager *helpers.ConfigManager, commandEventBus2 *events.CommandEventBus, tabHandler types.TabHandler) (*component.TextViewerComponent, error) {
	string2 := _wireStringValue
	textViewerComponent := component.NewTextViewerComponent(gui, string2, configManager, commandEventBus2, tabHandler)
	return textViewerComponent, nil
}

var (
	_wireStringValue = "Help"
)

func ProvideDiffViewerComponent(gui types.Gui, configManager *helpers.ConfigManager, commandEventBus2 *events.CommandEventBus, tabHandler types.TabHandler) (*component.DiffViewerComponent, error) {
	string2 := _wireStringValue2
	diffViewerComponent := component.NewDiffViewerComponent(gui, string2, configManager, commandEventBus2, tabHandler)
	return diffViewerComponent, nil
}

var (
	_wireStringValue2 = "Diff"
)

func ProvideDebugComponent(gui types.Gui, debugState *state.DebugState, configManager *helpers.ConfigManager, commandEventBus2 *events.CommandEventBus, tabHandler types.TabHandler) (*component.DebugComponent, error) {
	debugComponent := component.NewDebugComponent(gui, debugState, configManager, commandEventBus2, tabHandler)
	return debugComponent, nil
}

func ProvideDebugController(genieService genie.Genie, gui types.Gui, debugState *state.DebugState, debugComponent *component.DebugComponent, layoutManager *layout.LayoutManager, clipboard *helpers.Clipboard, configManager *helpers.ConfigManager, commandEventBus2 *events.CommandEventBus) (*controllers.DebugController, error) {
	debugController := controllers.NewDebugController(genieService, gui, debugState, debugComponent, layoutManager, clipboard, configManager, commandEventBus2)
	return debugController, nil
}

func ProvideChatController(messagesComponent *component.MessagesComponent, gui types.Gui, genieService genie.Genie, stateAccessor *state.StateAccessor, configManager *helpers.ConfigManager, commandEventBus2 *events.CommandEventBus, debugController *controllers.DebugController) (*controllers.ChatController, error) {
	chatController := controllers.NewChatController(messagesComponent, gui, genieService, stateAccessor, configManager, commandEventBus2, debugController)
	return chatController, nil
}

func ProvideLLMContextController(gui types.Gui, genieService genie.Genie, layoutManager *layout.LayoutManager, stateAccessor *state.StateAccessor, configManager *helpers.ConfigManager, commandEventBus2 *events.CommandEventBus, debugController *controllers.DebugController) (*controllers.LLMContextController, error) {
	llmContextController := controllers.NewLLMContextController(gui, genieService, layoutManager, stateAccessor, configManager, commandEventBus2, debugController)
	return llmContextController, nil
}

func ProvideToolConfirmationController(gui types.Gui, stateAccessor *state.StateAccessor, layoutManager *layout.LayoutManager, inputComponent *component.InputComponent, configManager *helpers.ConfigManager, eventBus events2.EventBus, commandEventBus2 *events.CommandEventBus, debugController *controllers.DebugController) (*controllers.ToolConfirmationController, error) {
	toolConfirmationController := controllers.NewToolConfirmationController(gui, stateAccessor, layoutManager, inputComponent, configManager, eventBus, commandEventBus2, debugController)
	return toolConfirmationController, nil
}

func ProvideUserConfirmationController(gui types.Gui, stateAccessor *state.StateAccessor, layoutManager *layout.LayoutManager, inputComponent *component.InputComponent, diffViewerComponent *component.DiffViewerComponent, configManager *helpers.ConfigManager, eventBus events2.EventBus, commandEventBus2 *events.CommandEventBus, debugController *controllers.DebugController) (*controllers.UserConfirmationController, error) {
	userConfirmationController := controllers.NewUserConfirmationController(gui, stateAccessor, layoutManager, inputComponent, diffViewerComponent, configManager, eventBus, commandEventBus2, debugController)
	return userConfirmationController, nil
}

// InjectTUI - Production TUI injector (default output mode from config)
func InjectTUI(session *genie.Session) (*TUI, error) {
	configManager, err := ProvideConfigManager()
	if err != nil {
		return nil, err
	}
	gui, err := NewGocuiGui(configManager)
	if err != nil {
		return nil, err
	}
	genieGenie, err := ProvideGenie()
	if err != nil {
		return nil, err
	}
	eventsCommandEventBus := ProvideCommandEventBus()
	app, err := NewApp(gui, genieGenie, session, eventsCommandEventBus, configManager)
	if err != nil {
		return nil, err
	}
	tui := New(app)
	return tui, nil
}

// InjectTestApp - Test App injector (custom output mode)
func InjectTestApp(genieService genie.Genie, session *genie.Session, outputMode gocui.OutputMode) (*App, error) {
	gui, err := NewGocuiGuiWithOutputMode(outputMode)
	if err != nil {
		return nil, err
	}
	eventsCommandEventBus := ProvideCommandEventBus()
	configManager, err := ProvideConfigManager()
	if err != nil {
		return nil, err
	}
	app, err := NewApp(gui, genieService, session, eventsCommandEventBus, configManager)
	if err != nil {
		return nil, err
	}
	return app, nil
}

// wire.go:

// HistoryPath represents the path to the chat history file
type HistoryPath string

// Shared command event bus instance
var commandEventBus = events.NewCommandEventBus()

// Shared genie instance (singleton)
var (
	genieInstance    genie.Genie
	genieError       error
	genieInitialized bool
)

// Shared GUI instance (singleton)
var (
	guiInstance    *gocui.Gui
	guiError       error
	guiInitialized bool
)

// ProvideCommandEventBus provides a shared command event bus instance
func ProvideCommandEventBus() *events.CommandEventBus {
	return commandEventBus
}

// ProvideGenie provides a shared Genie singleton instance
func ProvideGenie() (genie.Genie, error) {
	if !genieInitialized {
		genieInstance, genieError = di.ProvideGenie()
		genieInitialized = true
	}
	return genieInstance, genieError
}

// NewGocuiGui - Production GUI provider (uses config-based output mode)
func NewGocuiGui(configManager *helpers.ConfigManager) (*gocui.Gui, error) {
	config := configManager.GetConfig()
	guiOutputMode := configManager.GetGocuiOutputMode(config.OutputMode)

	g, err := gocui.NewGui(guiOutputMode, true)
	if err != nil {
		return nil, err
	}
	return g, nil
}

// NewGocuiGuiWithOutputMode - Test/Custom GUI provider (accepts custom output mode)
func NewGocuiGuiWithOutputMode(outputMode gocui.OutputMode) (*gocui.Gui, error) {
	g, err := gocui.NewGui(outputMode, true)
	if err != nil {
		return nil, err
	}
	return g, nil
}

// ProvideHistoryPath provides the chat history file path based on session working directory
func ProvideHistoryPath(session *genie.Session) HistoryPath {
	return HistoryPath(filepath.Join(session.WorkingDirectory, ".genie", "history"))
}

func ProvideChatState(configManager *helpers.ConfigManager) *state.ChatState {
	config := configManager.GetConfig()
	return state.NewChatState(config.MaxChatMessages)
}

func ProvideUIState() *state.UIState {
	return state.NewUIState()
}

func ProvideDebugState() *state.DebugState {
	return state.NewDebugState()
}

func ProvideStateAccessor(chatState *state.ChatState, uiState *state.UIState) *state.StateAccessor {
	return state.NewStateAccessor(chatState, uiState)
}

func ProvideTabHandler(app *App) types.TabHandler {
	return func(v *gocui.View) error {
		return app.nextView(app.gui, v)
	}
}

func ProvideGui(app *App) types.Gui {
	return &Gui{app: app}
}

func ProvideHistoryPathString(historyPath HistoryPath) string {
	return string(historyPath)
}

func ProvideEventBus(genieService genie.Genie) events2.EventBus {
	return genieService.GetEventBus()
}

func ProvideLayoutBuilder(
	gui *gocui.Gui,
	configManager *helpers.ConfigManager,
	messagesComponent *component.MessagesComponent,
	inputComponent *component.InputComponent,
	statusComponent *component.StatusComponent,
	textViewerComponent *component.TextViewerComponent,
	diffViewerComponent *component.DiffViewerComponent,
	debugComponent *component.DebugComponent,
) *LayoutBuilder {
	return NewLayoutBuilder(
		gui,
		configManager,
		messagesComponent,
		inputComponent,
		statusComponent,
		textViewerComponent,
		diffViewerComponent,
		debugComponent,
	)
}

// CoreDepsSet - Core dependencies (shared between production and test)
var CoreDepsSet = wire.NewSet(
	ProvideCommandEventBus,
)

// ProdAppDepsSet - Production app dependencies (includes config-based GUI)
var ProdAppDepsSet = wire.NewSet(
	CoreDepsSet,
	ProvideGenie,
	ProvideConfigManager,
	NewGocuiGui,
	NewApp,
)

// TestAppDepsSet - Test app dependencies (uses custom output mode GUI)
var TestAppDepsSet = wire.NewSet(
	CoreDepsSet,
	ProvideConfigManager,
	NewGocuiGuiWithOutputMode,
)
