// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package genie

import (
	"fmt"
	"github.com/kcaldas/genie/pkg/ai"
	"github.com/kcaldas/genie/pkg/config"
	"github.com/kcaldas/genie/pkg/ctx"
	"github.com/kcaldas/genie/pkg/events"
	"github.com/kcaldas/genie/pkg/llm/anthropic"
	"github.com/kcaldas/genie/pkg/llm/genai"
	"github.com/kcaldas/genie/pkg/llm/lmstudio"
	"github.com/kcaldas/genie/pkg/llm/multiplexer"
	"github.com/kcaldas/genie/pkg/llm/ollama"
	"github.com/kcaldas/genie/pkg/llm/openai"
	"github.com/kcaldas/genie/pkg/mcp"
	"github.com/kcaldas/genie/pkg/persona"
	"github.com/kcaldas/genie/pkg/prompts"
	"github.com/kcaldas/genie/pkg/skills"
	"github.com/kcaldas/genie/pkg/tools"
	"strings"
	"sync"
)

// Injectors from wire.go:

// ProvideGenie provides a complete Genie instance with a per-instance event bus.
func ProvideGenie() (Genie, error) {
	eventBus := provideNewEventBus()
	manager := ProvideConfigManager()
	gen, err := provideAIGen(eventBus, manager)
	if err != nil {
		return nil, err
	}
	bool2 := _wireBoolValue
	promptRunner := NewDefaultPromptRunner(gen, bool2)
	publisher := providePublisher(eventBus)
	sessionManager := NewSessionManager(publisher)
	skillsSkillManager, err := ProvideSkillManager()
	if err != nil {
		return nil, err
	}
	contextPartProviderRegistry := provideContextRegistry(eventBus, skillsSkillManager)
	contextManager := ctx.NewContextManager(contextPartProviderRegistry)
	todoManager := ProvideTodoManager()
	mcpClient, err := ProvideMCPClient()
	if err != nil {
		return nil, err
	}
	registry := tools.NewDefaultRegistry(eventBus, todoManager, skillsSkillManager, mcpClient)
	outputFormatter := tools.NewOutputFormatter(registry)
	loader := prompts.NewPromptLoader(publisher, registry)
	personaAwarePromptFactory := persona.NewPersonaPromptFactory(loader, skillsSkillManager)
	personaManager := persona.NewDefaultPersonaManager(personaAwarePromptFactory, manager, publisher)
	genie := newGenieCore(promptRunner, sessionManager, contextManager, eventBus, outputFormatter, personaManager, manager, registry)
	return genie, nil
}

var (
	_wireBoolValue = false
)

// ProvideGenieWithOptions provides a complete Genie instance with custom options
// and a per-instance event bus.
func ProvideGenieWithOptions(options *GenieOptions) (Genie, error) {
	eventBus := provideNewEventBus()
	manager := ProvideConfigManager()
	gen, err := provideAIGen(eventBus, manager)
	if err != nil {
		return nil, err
	}
	bool2 := _wireBoolValue2
	promptRunner := NewDefaultPromptRunner(gen, bool2)
	publisher := providePublisher(eventBus)
	sessionManager := NewSessionManager(publisher)
	skillsSkillManager, err := ProvideSkillManager()
	if err != nil {
		return nil, err
	}
	contextPartProviderRegistry := provideContextRegistry(eventBus, skillsSkillManager)
	contextManager := ctx.NewContextManager(contextPartProviderRegistry)
	todoManager := ProvideTodoManager()
	mcpClient, err := ProvideMCPClient()
	if err != nil {
		return nil, err
	}
	registry, err := newRegistryWithOptions(eventBus, todoManager, skillsSkillManager, mcpClient, options)
	if err != nil {
		return nil, err
	}
	outputFormatter := tools.NewOutputFormatter(registry)
	loader := prompts.NewPromptLoader(publisher, registry)
	personaAwarePromptFactory := persona.NewPersonaPromptFactory(loader, skillsSkillManager)
	personaManager := persona.NewDefaultPersonaManager(personaAwarePromptFactory, manager, publisher)
	genie := newGenieCore(promptRunner, sessionManager, contextManager, eventBus, outputFormatter, personaManager, manager, registry)
	return genie, nil
}

var (
	_wireBoolValue2 = false
)

// ProvideToolRegistry provides a tool registry (standalone, own event bus).
func ProvideToolRegistry() (tools.Registry, error) {
	eventBus := provideNewEventBus()
	todoManager := ProvideTodoManager()
	v, err := ProvideSkillManager()
	if err != nil {
		return nil, err
	}
	mcpClient, err := ProvideMCPClient()
	if err != nil {
		return nil, err
	}
	registry := tools.NewDefaultRegistry(eventBus, todoManager, v, mcpClient)
	return registry, nil
}

// ProvideOutputFormatter provides a tool output formatter (standalone).
func ProvideOutputFormatter() (tools.OutputFormatter, error) {
	registry, err := ProvideToolRegistry()
	if err != nil {
		return nil, err
	}
	outputFormatter := tools.NewOutputFormatter(registry)
	return outputFormatter, nil
}

// ProvidePromptLoader provides a prompt loader (standalone, own event bus).
func ProvidePromptLoader() (prompts.Loader, error) {
	eventBus := provideNewEventBus()
	publisher := providePublisher(eventBus)
	registry, err := ProvideToolRegistry()
	if err != nil {
		return nil, err
	}
	loader := prompts.NewPromptLoader(publisher, registry)
	return loader, nil
}

// ProvideGen provides an AI Gen (standalone, own event bus).
func ProvideGen() (ai.Gen, error) {
	eventBus := provideNewEventBus()
	manager := ProvideConfigManager()
	gen, err := provideAIGen(eventBus, manager)
	if err != nil {
		return nil, err
	}
	return gen, nil
}

// ProvidePromptRunner provides a prompt runner (standalone).
func ProvidePromptRunner() (PromptRunner, error) {
	gen, err := ProvideGen()
	if err != nil {
		return nil, err
	}
	bool2 := _wireBoolValue3
	promptRunner := NewDefaultPromptRunner(gen, bool2)
	return promptRunner, nil
}

var (
	_wireBoolValue3 = false
)

// ProvideSessionManager provides a session manager (standalone, own event bus).
func ProvideSessionManager() SessionManager {
	eventBus := provideNewEventBus()
	publisher := providePublisher(eventBus)
	sessionManager := NewSessionManager(publisher)
	return sessionManager
}

// ProvideContextManager provides a context manager (standalone, own event bus).
func ProvideContextManager() (ctx.ContextManager, error) {
	eventBus := provideNewEventBus()
	skillsSkillManager, err := ProvideSkillManager()
	if err != nil {
		return nil, err
	}
	contextPartProviderRegistry := provideContextRegistry(eventBus, skillsSkillManager)
	contextManager := ctx.NewContextManager(contextPartProviderRegistry)
	return contextManager, nil
}

// ProvidePersonaManager provides a persona manager (standalone).
func ProvidePersonaManager() (persona.PersonaManager, error) {
	eventBus := provideNewEventBus()
	publisher := providePublisher(eventBus)
	registry, err := ProvideToolRegistry()
	if err != nil {
		return nil, err
	}
	loader := prompts.NewPromptLoader(publisher, registry)
	skillsSkillManager, err := ProvideSkillManager()
	if err != nil {
		return nil, err
	}
	personaAwarePromptFactory := persona.NewPersonaPromptFactory(loader, skillsSkillManager)
	manager := ProvideConfigManager()
	personaManager := persona.NewDefaultPersonaManager(personaAwarePromptFactory, manager, publisher)
	return personaManager, nil
}

// wire.go:

// Shared skill manager instance (lazy initialized)
var (
	skillManager     skills.SkillManager
	skillManagerOnce sync.Once
	skillManagerErr  error
)

// provideNewEventBus creates a fresh event bus for each Genie instance.
func provideNewEventBus() events.EventBus {
	return events.NewEventBus()
}

// providePublisher adapts EventBus to Publisher interface for Wire.
func providePublisher(eb events.EventBus) events.Publisher {
	return eb
}

// provideSubscriber adapts EventBus to Subscriber interface for Wire.
func provideSubscriber(eb events.EventBus) events.Subscriber {
	return eb
}

// ProvideTodoManager provides a shared todo manager instance
func ProvideTodoManager() tools.TodoManager {
	return tools.NewTodoManager()
}

// ProvideSkillManager provides a shared skill manager instance
func ProvideSkillManager() (skills.SkillManager, error) {
	skillManagerOnce.Do(func() {
		skillManager, skillManagerErr = skills.NewDefaultSkillManager()
	})
	return skillManager, skillManagerErr
}

// ProvideMCPClient provides a lazy MCP client (uninitialized until registry.Init is called)
func ProvideMCPClient() (tools.MCPClient, error) {
	return mcp.NewLazyMCPClient(), nil
}

// ProvideConfigManager provides a configuration manager
func ProvideConfigManager() config.Manager {
	return config.NewConfigManager()
}

// newRegistryWithOptions is a provider function that creates a registry based on options
func newRegistryWithOptions(
	eventBus events.EventBus,
	todoManager tools.TodoManager, skillManager2 tools.SkillManager,

	mcpClient tools.MCPClient,
	options *GenieOptions,
) (tools.Registry, error) {
	if options.CustomRegistry != nil {
		return options.CustomRegistry, nil
	}

	if options.CustomRegistryFactory != nil {
		return options.CustomRegistryFactory(eventBus, todoManager), nil
	}

	registry := tools.NewDefaultRegistry(eventBus, todoManager, skillManager2, mcpClient)

	for _, tool := range options.CustomTools {
		if err := registry.Register(tool); err != nil {
			return nil, fmt.Errorf("failed to register custom tool: %w (hint: check .mcp.json for conflicting tool names)", err)
		}
	}

	return registry, nil
}

// provideAIGen creates the AI Gen with the given event bus (per-instance).
func provideAIGen(eb events.EventBus, configManager config.Manager) (ai.Gen, error) {
	provider := strings.ToLower(configManager.GetStringWithDefault("GENIE_LLM_PROVIDER", "genai"))

	factories := map[string]multiplexer.Factory{
		"genai":     func() (ai.Gen, error) { return genai.NewClient(eb) },
		"openai":    func() (ai.Gen, error) { return openai.NewClient(eb) },
		"anthropic": func() (ai.Gen, error) { return anthropic.NewClient(eb) },
		"ollama":    func() (ai.Gen, error) { return ollama.NewClient(eb) },
		"lmstudio":  func() (ai.Gen, error) { return lmstudio.NewClient(eb) },
	}

	aliases := map[string]string{
		"gemini":           "genai",
		"google":           "genai",
		"vertex":           "genai",
		"openai-chat":      "openai",
		"claude":           "anthropic",
		"anthropic-claude": "anthropic",
		"lm-studio":        "lmstudio",
	}

	muxClient, err := multiplexer.NewClient(provider, factories, aliases)
	if err != nil {
		return nil, err
	}

	if err := muxClient.WarmUp(provider); err != nil {
		return nil, err
	}

	baseGen := ai.Gen(muxClient)
	captureProvider := muxClient.DefaultProvider()

	captureConfig := ai.GetCaptureConfigFromEnv(captureProvider)
	if captureConfig.Enabled {
		baseGen = ai.NewCaptureMiddleware(baseGen, captureConfig)
	}

	retryConfig := ai.GetRetryConfigFromEnv(configManager)
	if retryConfig.Enabled {
		return ai.NewRetryMiddleware(baseGen, retryConfig), nil
	}

	return baseGen, nil
}

// provideContextRegistry creates the context registry using the given event bus.
func provideContextRegistry(
	eb events.EventBus, skillManager2 skills.SkillManager,

) *ctx.ContextPartProviderRegistry {
	registry := ctx.NewContextPartProviderRegistry()

	projectManager := ctx.NewProjectCtxManager(eb)
	chatManager := ctx.NewChatCtxManager(eb)
	fileProvider := ctx.NewFileContextPartsProvider(eb)
	todoProvider := ctx.NewTodoContextPartProvider(eb)
	skillProvider := skills.NewSkillContextPartProvider(skillManager2, eb)

	chatManager.SetBudgetStrategy(ctx.NewSlidingWindowStrategy())
	fileProvider.SetCollectionStrategy(ctx.NewLRUStrategy(10))
	fileProvider.SetContentStrategy(ctx.NewSoftTrimStrategy(1500, 1500))

	registry.Register(projectManager, 0)
	registry.Register(chatManager, 0.7)
	registry.Register(fileProvider, 0.3)
	registry.Register(todoProvider, 0)

	if skillProvider != nil {
		registry.Register(skillProvider, 0)
	}

	return registry
}
